name: Node.js CI
on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm install
      - run: npm run build
      # - run: npm run generate
      - run: npm run cname
      # - run: npm test
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: .output/public
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      # - name: Mirror
      #   run: |
      #     git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com:EasonC13/CV_Academic.git
      #     cd CV_Academic
      #     git config --global user.name 'Your Name'
      #     git config --global user.email 'your-username@users.noreply.github.com'
      #     git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com:EasonC13/eason.phd.git
      #     sed "s/'eason.best'/'eason.phd'/g" package.json > new_file.txt && mv new_file.txt package.json && rm new_file.txt
      #     git add package.json && git commit -m "eason.phd"
      #     git push -f --mirror git@github.com:EasonC13/eason.phd.git
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}